### ISSUE TITLE
How Can I convert this model to TFLITE

### ISSUE THREAD

**Issue by kei9327** [akirasosa/mobile-semantic-segmentation#37]
I want to build Android App.

So I use Tensorflow Lite for Android.

But I can't get .tflite file.

How Can I convert this model to TFLITE?

**Comment by kei9327** [comment]
@akirasosa please help

**Comment by kei9327** [comment]
Thanks @sercant 

But I hav some problem... 

in Shell...
`Traceback (most recent call last):
  File "tf-convert-tflite.py", line 89, in <module>
    main(**vars(args))
  File "tf-convert-tflite.py", line 47, in main
    tflite_model = converter.convert()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 439, in convert
    **converter_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 309, in toco_convert_impl
    input_data.SerializeToString())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 109, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
/bin/sh: toco_from_protos: command not found

None
`

I can't handling this shell error... So How can i do solve this problem?

**Comment by kei9327** [comment]
> Thanks @sercant
> 
> But I hav some problem...
> 
> in Shell...
> ``Traceback (most recent call last):
> File "tf-convert-tflite.py", line 89, in 
> main(**vars(args))
> File "tf-convert-tflite.py", line 47, in main
> tflite_model = converter.convert()
> File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 439, in convert
> **converter_kwargs)
> File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 309, in toco_convert_impl
> input_data.SerializeToString())
> File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 109, in toco_convert_protos
> (stdout, stderr))
> RuntimeError: TOCO failed see console for info.
> /bin/sh: toco_from_protos: command not found
> 
> None
> ``
> 
> I can't handling this shell error... So How can i do solve this problem?

**Comment by akirasosa** [comment]
Hi, I have rewrite code using PyTorch and tf-lite is TODO now.

**Comment by ldenoue** [comment]
did you notice better accuracy when using pytorch?

**Comment by kei9327** [comment]
> > Thanks @sercant
> > But I hav some problem...
> > in Shell...
> > ```
> > Traceback (most recent call last):
> >   File "tf-convert-tflite.py", line 89, in <module>
> >     main(**vars(args))
> >   File "tf-convert-tflite.py", line 47, in main
> >     tflite_model = converter.convert()
> >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 439, in convert
> >     **converter_kwargs)
> >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 309, in toco_convert_impl
> >     input_data.SerializeToString())
> >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 109, in toco_convert_protos
> >     (stdout, stderr))
> > RuntimeError: TOCO failed see console for info.
> > /bin/sh: toco_from_protos: command not found
> > 
> > None
> > ```
> > I can't handling this shell error... So How can i do solve this problem?
> 
> Maybe it's because of the python or tensorflow version difference. I am using Python 3.6.5 and Tensorflow 1.12.0.


If it's not an excuse, Do you have any pretrain data (TFLite)?

**Comment by sercant** [comment]
> > > Thanks @sercant
> > > But I hav some problem...
> > > in Shell...
> > > ```
> > > Traceback (most recent call last):
> > >   File "tf-convert-tflite.py", line 89, in <module>
> > >     main(**vars(args))
> > >   File "tf-convert-tflite.py", line 47, in main
> > >     tflite_model = converter.convert()
> > >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 439, in convert
> > >     **converter_kwargs)
> > >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 309, in toco_convert_impl
> > >     input_data.SerializeToString())
> > >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 109, in toco_convert_protos
> > >     (stdout, stderr))
> > > RuntimeError: TOCO failed see console for info.
> > > /bin/sh: toco_from_protos: command not found
> > > 
> > > None
> > > ```
> > > I can't handling this shell error... So How can i do solve this problem?
> > 
> > 
> > Maybe it's because of the python or tensorflow version difference. I am using Python 3.6.5 and Tensorflow 1.12.0.
> 
> If it's not an excuse, Do you have any pretrain data (TFLite)?

[Here](https://drive.google.com/open?id=1XfkItk27mll4vqLLnDMHS9Dcs0hOUOms) is the one I converted using shared pre-trained model.

**Comment by normandra** [comment]
@sercant how did the model performed on your implementation? I just tried this today and it performed really bad... not only is it slow ~1100ms it also just tries to predict a hair in the middle of the screen everytime.

**Comment by sercant** [comment]
> @sercant how did the model performed on your implementation? I just tried this today and it performed really bad... not only is it slow ~1100ms it also just tries to predict a hair in the middle of the screen everytime.

Yes, it was the same case for me regarding both performance and the behavior. I don't know why it tries to find a hair in the middle of the screen all the time. Maybe the checkpoint provided in #17 was overfitted.

**Comment by chin87** [comment]
> Thanks @sercant
> 
> But I hav some problem...
> 
> in Shell...
> 
> ```
> Traceback (most recent call last):
>   File "tf-convert-tflite.py", line 89, in <module>
>     main(**vars(args))
>   File "tf-convert-tflite.py", line 47, in main
>     tflite_model = converter.convert()
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 439, in convert
>     **converter_kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 309, in toco_convert_impl
>     input_data.SerializeToString())
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 109, in toco_convert_protos
>     (stdout, stderr))
> RuntimeError: TOCO failed see console for info.
> /bin/sh: toco_from_protos: command not found
> 
> None
> ```
> I can't handling this shell error... So How can i do solve this problem?

has anyone solved this error, i'm getting same error for my model

**Comment by sercant** [comment]
> > Thanks @sercant
> > But I hav some problem...
> > in Shell...
> > ```
> > Traceback (most recent call last):
> >   File "tf-convert-tflite.py", line 89, in <module>
> >     main(**vars(args))
> >   File "tf-convert-tflite.py", line 47, in main
> >     tflite_model = converter.convert()
> >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 439, in convert
> >     **converter_kwargs)
> >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 309, in toco_convert_impl
> >     input_data.SerializeToString())
> >   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 109, in toco_convert_protos
> >     (stdout, stderr))
> > RuntimeError: TOCO failed see console for info.
> > /bin/sh: toco_from_protos: command not found
> > 
> > None
> > ```
> > I can't handling this shell error... So How can i do solve this problem?
> 
> has anyone solved this error, i'm getting same error for my model

Hey @chin87, I think this is due to a bug in Tensorflow right now. Be sure that `toco_from_protos` is in your `PATH` variable.

Also, I have an updated version of the script at [my repo](https://github.com/sercant/mobile-segmentation/blob/master/export_tflite.py) if you want to check it out. You will need to modify it to work with this repo though.

**Comment by charliesantos** [comment]
Hi @sercant @akirasosa sorry for bringing up this 2 year old issue. Any news on adding a script to convert to tflite?
@sercant , does your script still works with this repo? Thank you in advance!
